### ISSUE TITLE
TZComet doesn't support text/html as MIME type

### ISSUE THREAD

**Issue by damian0815** [oxheadalpha/TZComet#85]
Using the token explorer to browse `KT1WmAHNFxV1JzoGxQYEkE1aFKvNNNSj73sX`, for example token id `10000000003` fails to display the html content.

eg https://tzcomet.io/#/token/KT1WmAHNFxV1JzoGxQYEkE1aFKvNNNSj73sX/10000000003%3Fexplorer-input%3DKT1WmAHNFxV1JzoGxQYEkE1aFKvNNNSj73sX - expanding "show logs" it seems that the URL https://mainnet.live.endlessways.net/10000000003 has been correctly discovered, but it does not render, presumably because the MIME type is text/html. 

(What would be expected/ideal in this case is an `iframe` that renders the content!)

**Comment by damian0815** [comment]
ooh, just saw #84 - a small tweak to that and it would fix this too

**Comment by damian0815** [comment]
fwiw this problem also effects tokens like Geoff Stearns's h3p <https://h3p.deconcept.com> (eg https://tzcomet.io/#/token/KT1Fxz4V3LaUcVFpvF8pAAx8G3Z4H7p7hhDg/1%3Fexplorer-input%3DKT1Fxz4V3LaUcVFpvF8pAAx8G3Z4H7p7hhDg)

**Comment by smondet** [comment]
![screenshot-20220225-155937](https://user-images.githubusercontent.com/617111/155802217-86a8f0ee-6143-4bfa-aadc-948b017cc790.png)

This is fixed now! (#84)
