### ISSUE TITLE
Regression - token ids >INT32 not supported in main contract explorer

### ISSUE THREAD

**Issue by damian0815** [oxheadalpha/TZComet#86]
Seems there has been a regression of #71 at some point - it's not possible to look at metadata for a single token on `KT1WmAHNFxV1JzoGxQYEkE1aFKvNNNSj73sX` , eg token with id `10000000003` - i have to use the `all_tokens` checkbox and get metadata for everything

**Comment by smondet** [comment]
This was also fixed in #84 

![screenshot-20220225-160110](https://user-images.githubusercontent.com/617111/155802437-07fce07e-d36d-4e0a-bd44-bc2f7e00ea7e.png)

**Comment by damian0815** [comment]
thanks for both!
